<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JewelleryStore.Modules.Catalog.Application\JewelleryStore.Modules.Catalog.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="EntryPointAdapters\Rest\Middlewares\" />
    <Folder Include="Injections\" />
    <Folder Include="OutputPointAdapters\Database\SqlServer\" />
  </ItemGroup>

</Project>
