<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="EntryPointAdapters\Rest\Controllers\" />
    <Folder Include="EntryPointAdapters\Rest\Middlewares\" />
    <Folder Include="Injections\" />
    <Folder Include="OutputPointAdapters\Database\SqlServer\" />
  </ItemGroup>

</Project>
